### ISSUE TITLE
ember-fetch lowercases header keys

### ISSUE THREAD

**Issue by tomasz-szymanek** [ember-cli/ember-fetch#100]
```
import fetch from "ember-fetch";

const url = ...
const headers = { ...headers, "Content-Type": "xxx/yyy" };

fetch(url, {
  headers
})
```

results in request with header "content-type", which is not working, since headers keys are case sensitive.

**Comment by tchak** [comment]
https://tools.ietf.org/html/rfc7230#section-3.2

`Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.`

**Comment by tchak** [comment]
`fetch` implementations systematically lowercase header keys

**Comment by tomasz-szymanek** [comment]
Thank you for explanation.
