### ISSUE TITLE
Ember-fetch incorrectly handles HTTP 303 status 

### ISSUE THREAD

**Issue by tomasz-szymanek** [ember-cli/ember-fetch#105]
1. Perform POST 
2. backend responds with HTTP Status 303
3. An automatic redirect to new resource (from Location Header) is done
4. we get proper response, but in order to be able to do totally different request in the future, we need access to either mentioned LocationHeader or to URL of redirected  request.

Because the redirect is done, it is not possible to get access to LocationHeader, ember-fetch in response object returns URL of initial (POST) request and not the one after redirect, so we use normal fetch in order to get proper URL from received response object.

**Comment by nlfurniss** [comment]
I just tried this, and the `url` returned in the `Response` is the correct one.

```js
fetch('https://www.mocky.io/v2/5a8520933000006e0069b0fa', {
  method: 'POST'
})
.then(response => console.log(response));
```

```
// Response object
body: (...),
bodyUsed: false,
headers: Headers {},
ok: true,
redirected: true,
status: 200,
statusText: "OK",
type: "basic",
url: "https://www.mocky.io/"
```

Are there any other important details?

**Comment by n1klu5** [comment]
Using exactly the same code you pasted
```
fetch('https://www.mocky.io/v2/5a8520933000006e0069b0fa', {
  method: 'POST'
})
.then(response => console.log(response));
```

We get the response using ember-fetch
```
//Response object
headers: Headers {map: {…}}
ok: true
status: 200
statusText: "OK"
type: "default"
url: ""
_bodyInit "↵↵↵↵<!DOCTYPE html>↵↵<html>↵  ..."
_bodyText"↵↵↵↵<!DOCTYPE html>↵↵<html>↵  ..."
__proto__: Object
```

Are you sure you used ember-fetch? Because your response object looks like response from standard fetch not like the one from ember-fetch

**Comment by nlfurniss** [comment]
I am sure, as I added that code to `ember-fetch`'s dummy app. Here is a screenshot of it hitting the polyfill:

![image](https://user-images.githubusercontent.com/1477357/36479383-6028ff46-16bd-11e8-98cc-66c57df044aa.png)

And the response, complete with `url`:
![image](https://user-images.githubusercontent.com/1477357/36479410-7ffc64b6-16bd-11e8-9f92-b324d750220b.png)

**Comment by n1klu5** [comment]
OK, thank you for your input, you made me think :)
It looks like pretender (ember-cli-mirage is based on) is doing the bad work

**Comment by nlfurniss** [comment]
@tomasz-szymanek is your issue in app code or tests?

**Comment by tomasz-szymanek** [comment]
As @n1klu5 said - it wat mirage all along :) Thanks for your time!
