### ISSUE TITLE
findAll hangs with ember-fetch + Ember 3.1 beta

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-fetch#106]
I am using the prescribed workarounds from the README to get things working with fastboot with the ajax initializer noop and ember-data with the adapter mixin, which has worked great, until now. After updating to Ember 3.1, my `this.store.findAll` calls all the sudden just hang forever. They do not error out, but just seem to never resolve or something. I believe the issue lies with ember-fetch, but it could be the setup has changed and just needs some tweaks. I also opened an issue for fastboot here https://github.com/ember-fastboot/ember-cli-fastboot/issues/575. Any ideas on what could be happening?

**Comment by nlfurniss** [comment]
Which version of ember and ember data were you using when everything still worked?

**Comment by rwwagner90** [comment]
@nlfurniss everything worked on Ember 3.0.0 and ember-data 3.0.1 I believe. The ember-data version does not seem to make a difference. I tried downgrading ember-data and the issues persisted. The only thing that made it work again was downgrading Ember itself to 3.0.0 or before.

**Comment by nlfurniss** [comment]
So i spun up [a test app](https://github.com/nlfurniss/ember-fastboot-test-app) with:

- ember-source v3.1.0-beta1
- ember-data 3.1.0-beta.1
- ember-cli-fastboot 1.1.2 (plus overriding `ajax-service` initializer)
- ember-fetch 3.4.4

With `ember-fetch` being used, the page hangs and never loads. If you remove the `ajax-service` override, you get the known error from ember-fetch

@stefanpenner lets discuss soon.

**Comment by rwwagner90** [comment]
Thanks for throwing that together @nlfurniss! Please let me know if there is anything I can do to help. I was unsure how to debug since it was hanging and not erroring.

**Comment by nlfurniss** [comment]
I did a test and found that if i goto the `/users` route of my test app directly, it hangs. But if I click a link from `index` to that route, it loads just fine.

@rwwagner90, can you confirm?

**Comment by nlfurniss** [comment]
Narrowed down the cause a tiny bit.

The promise returned from [router.handleURL](https://github.com/emberjs/ember.js/blob/9300d1b7d3aa70987986b1997ecf02a542ea49be/packages/ember-routing/lib/system/router.js#L348) isn't returning (it's being [called from here](https://github.com/emberjs/ember.js/blob/8be1a9d1d4fbbefda5623efa9c35ffadcf127802/packages/ember-application/lib/system/application-instance.js#L269)).

[This is the point](https://github.com/ember-fastboot/fastboot/blob/fadd1668c250025495bc6a8bd80538ee680001e6/src/ember-app.js#L260) in `fastboot` where things crap out b/c of that. I also updated Ember to 3.1.0-beta.3, issue still persists.

cc @rwjblue @stefanpenner

**Comment by nlfurniss** [comment]
I upgraded to ember-source to `3.1.0-beta.5` and the issue seems to be gone. @rwwagner90 can you please confirm.

**Comment by rwwagner90** [comment]
@nlfurniss I have since removed ember-data from my app because I didn't really need it, and I am using ember-fetch directly now. If it works for you, I'd say it's probably good to go. We should likely add a test around whatever the failure was though, to ensure there are no regressions.
