### ISSUE TITLE
Adapter mixin causes error when API returns empty object & 204

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-fetch#107]
Getting this ember-data error after migrating to fetch and using the adapter mixin: `Assertion Failed: normalizeResponse must return a valid JSON API document: One or more of the following keys must be present: "data", "errors", "meta".`

This happens when the API returns a 204 response, but with an empty objects as the payload (`"{}"`). Our real API actually doesn't do this, but Mirage's default handler for `DELETE` calls seems to return this. 

It seems this was caused by #60, which changed the way a 204 response is handled in `determineBodyPromise()`.

jQuery's ajax seems to handle this differently. The raw xhr object has a status of 204 and `"{}"` as the `responseText`, but the success hook nevertheless receives `undefined` as the payload, as can be seen on this screenshot:

![image](https://user-images.githubusercontent.com/1325249/37787092-805f661c-2dfe-11e8-8a90-1b4dae0b242d.png)

To be a drop-in replacement, I think this should behave the same way as before, i.e. return `undefined` (or maybe `{ data: null }` as it was before)!?

**Comment by nlfurniss** [comment]
hey @simonihmig!

Seems like something that should be changed in Mirage. According to [httpstatus](https://httpstatuses.com/204), `A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.`

The logic in ember-fetch assumes that a 204 is being implemented this way

**Comment by simonihmig** [comment]
@nlfurniss hey, yes, I should probably create an issue for mirage as well. But I nevertheless think this could maybe be handled a bit better here as well, i.e. ignore any payload in the adapter mixin for a 204 response. Don't you think?

**Comment by tchak** [comment]
I just want to mention that we are moving fetch support to Ember Data itself : https://github.com/emberjs/data/pull/5386

**Comment by xg-wang** [comment]
Hi @simonihmig 
> To be a drop-in replacement, I think this should behave the same way as before, i.e. return undefined (or maybe { data: null } as it was before)!?

But the PR (it's same as now) you linked, the handling is to return `{ data: null }`

```js
if (response.ok && (status === 204 || status === 205 || requestData.method === 'HEAD')) {
    payload = { data: null };
}
```

Is it the expected output? Or the payload should be an empty string in 204 case?

**Comment by simonihmig** [comment]
Closing this, as this has been fixed in Mirage, and the fetch adapter mixin is deprecated anyway.
