### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-fetch#110]
How can I use this with fastboot / node-fetch? I always get `Only absolute URLs are supported` when trying to fetch `/foo`. This works in the browser, but not in fastboot.

**Comment by rwjblue** [comment]
Great question! There are things that could to do resolve, but I think the fundamental issue is that when running fastboot the app itself does not have awareness of _where_ it is being served from. Therefore it can’t know current protocol (e.g. for `//foo.com` style URLs) or host (e.g. `/path` type URLs). 

To fix this we would need an API from fastboot to be told where we are being served from. I personally can’t recall if that is already a “thing” we support (quick search didn’t lead to an answer). 

@kratiahuja - Do you recall?

**Comment by ryanto** [comment]
You would have to wrap fetch, build an absolute url, and then call the original fetch with the full url.

@dfreeman did something like this in addon docs: https://github.com/ember-learn/ember-cli-addon-docs/pull/179

**Comment by tchak** [comment]
Like @ryanto said, in order for `fetch` (or `najax` for that matter) to use relative requests it needs access to `fastboot` service, so the only way right now is to use a service to make your requests. I think it might be possible to dereference request information from `fastboot` service as a global in an `instance-initializer`, but seems hakish...

I have an addon with a fetch service https://github.com/tchak/ember-fetch-adapter
It obviously needs more docs...

**Comment by tchak** [comment]
And `ember-data` will do it for you too: https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1081-L1103

**Comment by tchak** [comment]
@rwwagner90 oh I absolutely agree with you we need better support for this without `ember-data`.

@rwjblue or @kratiahuja do you think it would be reasonable to expose request information on the global `FastBoot`?

**Comment by Caltor** [comment]
@rwwagner90 totally agree. Our team has never got to grips with / seen the benefit of ember data.

**Comment by rwwagner90** [comment]
@tchak I tried your service and it threw an error. I opened an issue. https://github.com/tchak/ember-fetch-adapter/issues/1

**Comment by xg-wang** [comment]
Closed by https://github.com/ember-cli/ember-fetch/pull/143
