### ISSUE TITLE
Installing ember-fetch breaks source maps for prod builds

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-fetch#119]
Demo: https://github.com/buschtoens/ember-fetch-sourcemap-bug

Installing ember-fetch breaks source maps for prod builds (i.e. builds with minification enabled).

During the build, the following warning is emitted:

```
[WARN] (broccoli-uglify-sourcemap) "ember-fetch.map" referenced in "assets/vendor.js" could not be found
```

Source map output without ember-fetch:

```json
{"version":3,"sources":["vendor/ember-cli/vendor-prefix.js","vendor/loader/loader.js","vendor/ember-resolver/legacy-shims.js", ...
```

Source map output with ember-fetch:

```json
{"version":3,"sources":["0"],"names":["window","Ember ...
```

**Comment by buschtoens** [comment]
The problem was introduced with v4.0.0.

While warning about deprecations, the source map gets built correctly:
```
yarn add -D 'ember-fetch@<4' && ember build -prod && head -c 500 ./dist/assets/vendor*.map
```

**Comment by buschtoens** [comment]
Which is weird, because according to [`v3.4.4...v4.0.0`](https://github.com/ember-cli/ember-fetch/compare/v3.4.4...v4.0.0) there is no difference between v3.4.5 and v4.0.0. 🤔

**Comment by buschtoens** [comment]
Oops, it's not `v3.4.4...v4.0.0`. I was tired yesterday, sorry 😄. Looking for the right version now.

**Comment by buschtoens** [comment]
It's [`v4.0.0...v4.0.1`](https://github.com/ember-cli/ember-fetch/compare/v4.0.0...v4.0.1).

Works:

```
yarn add -D ember-fetch@4.0.0 && ember build -prod && head -c 500 ./dist/assets/vendor*.map
```

Breaks:

```
yarn add -D ember-fetch@4.0.1 && ember build -prod && head -c 500 ./dist/assets/vendor*.map
```

Therefore #112 (#111) bricked it. 🙁

**Comment by buschtoens** [comment]
I guess the file ends up [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/default-packager.js#L1427-L1435) and `broccoli-concat` itself is probably not aware of source maps when joining files.

So I guess passing `sourceMapConfig: { enabled: false }` is indeed the correct solution to this problem.

**Comment by xg-wang** [comment]
@stefanpenner @tchak see comment here https://github.com/broccolijs/broccoli-concat/issues/123#issuecomment-403369315 
Any thoughts about this?

**Comment by xg-wang** [comment]
Under repo `https://github.com/buschtoens/ember-fetch-sourcemap-bug`.
```
rm yarn.lock
yarn install
ember b -prod
```

No more `Building[WARN] (broccoli-uglify-sourcemap) "ember-fetch.map" referenced in "assets/vendor.js" could not be found`
