### ISSUE TITLE
Credentials are always set as 'same-origin'

### ISSUE THREAD

**Issue by mdbiscan** [ember-cli/ember-fetch#123]
I'm spiking out a project to use Simple Auth, Fastboot, and Fetch with DRF adapters. I have to send a httpOnly cookie, as we're currently not using tokens other than CSRF. I'm able to set `X-CSRFToken` via headers, but I can't get around setting `'credentials':'include'`, as the AdapterFetch mixin always sets it as `same-origin`.

In `mungOptionsForFetch`: 

```javascript
const options = combineObjs({
    credentials: 'same-origin',
  }, _options);
```

I'm curious as to why credentials cannot be overridden? I can override `ajaxOptions` method and use my own options munger, but that seems a bit much for something that should be simple.

**Comment by nlfurniss** [comment]
Hey @mdbiscan!

They can be overridden, and defining your own `ajaxOptions` is how it's meant to be done. Inside you set any options you want and then call `super`. No need to define your own munger.

Example:
```js
// adapters/application.js (or whatever adapter you want this to apply to)

export default DS.RESTAdapter.extend(AdapterFetch, {
  ...

  ajaxOptions(url, type, _options) {
    let options = assign({ credentials: 'include' }, _options);

    this._super(url, type, options);
  }

```

**Comment by mdbiscan** [comment]
Hey @nlfurniss, thanks for your response.

Overriding `ajaxOptions` is what I've done, but it seems the way you're doing it here would get overwritten in the following line after you pass through super, no?

```
const options = combineObjs({
    credentials: 'same-origin',
  }, _options);
```

**Comment by nlfurniss** [comment]
Since it's not an official property of an Ember Data adapter, I don't think we want to add it to this mixin, as it's meant to be pretty plug and play.

**Comment by mdbiscan** [comment]
Thanks for the clarification!
