### ISSUE TITLE
Rollup issues

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-fetch#127]
Just tried 5.1.2 and hit:

```
  - broccoliBuilderErrorStack: ReferenceError: [BABEL] /Users/rwwagner/shipshape/shipshape.io/tmp/rollup-cache_path-q3trla78.tmp/build/src/x.js: Unknown option: direct.presets
    at error (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-fetch/node_modules/rollup/dist/rollup.js:224:15)
    at Object.error (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-fetch/node_modules/rollup/dist/rollup.js:17174:21)
    at /Users/rwwagner/shipshape/shipshape.io/node_modules/ember-fetch/node_modules/rollup/dist/rollup.js:17183:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - codeFrame: [BABEL] /Users/rwwagner/shipshape/shipshape.io/tmp/rollup-cache_path-q3trla78.tmp/build/src/x.js: Unknown option: direct.presets
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Rollup` plugin. 💥
```

**Comment by xg-wang** [comment]
@rwwagner90 Can you share a repro? I'm doing `ember b` on https://github.com/shipshapecode/shipshape.io/tree/master but no error.

This seems to be a babel version conflict (6 vs 5) https://github.com/babel/babel/issues/3838

**Comment by rwwagner90** [comment]
@xg-wang it only happens on Ember/Ember-CLI 3.4.0 beta, specifically beta 3.

**Comment by xg-wang** [comment]
@rwwagner90 Fixed by doing `yarn add babel-core@6`
It's caused by `ember-service-worker` on `ember-cli-babel`@5
https://github.com/DockYard/ember-service-worker/issues/126

I guess it somehow messed up the resolve path.

**Comment by rwwagner90** [comment]
Yep, seems to be fixed if I update everything, sorry about that!
