### ISSUE TITLE
Not working with Fastboot and ember-data

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-fetch#138]
I've followed the documentation to add the initializer in `fastboot/initializer/ajax.js`

```js
export default {
  name: 'ajax-service',
  initialize() {
    // noop
    // This is to override Fastboot's initializer which prevents ember-fetch from working
    // https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js
  }
}
```

and adding the `AdapterFetch` mixin to my `adapters/application.js`

```js
import DS from 'ember-data';
import AdapterFetch from 'ember-fetch/mixins/adapter-fetch';

export default DS.JSONAPIAdapter.extend(AdapterFetch, {
});
```

But am still getting an error message

`TypeError: Only absolute URLs are supported`

Looking into this error I've seen that there is already an issue relating to it
https://github.com/ember-cli/ember-fetch/issues/110

And also a PR which looks to address it
https://github.com/ember-cli/ember-fetch/pull/128

But I cannot determine the correct path to resolving the issue.

In the comments of the issue there is a suggestion that this is fixed for `ember-data` but I don't see how to achieve this.

The PR seems out of date now due to so many subsequent commits so I tried to fork the `ember-fetch` repo and make the changes myself.

So I added `ember-fetch-adapter` as a dependency to the `package.json` and updating `addon/mixins/adapter-fetch.js` to use the adapter instead, by including the service in the mixin

```js
  adapter: service(),
```

and using the adapter service in the fetch request

```
  _fetchRequest(url, options) {
    return this.adapter.fetch(url, options);
  },
```

But this now gives another error

`Error: Assertion Failed: Attempting to inject an unknown injection: 'service:adapter'`

I'm now at a loss as to how I can resolve this and to get `ember-fetch` working with `ember-data` and Fastboot.

I'm open to any solution, is this absolute URL issue fixable yet?

**Comment by scottkidder** [comment]
I'm running into this as well, although I haven't yet tried ember-fetch-adapter.

**Comment by scottkidder** [comment]
I can confirm #128 fixes the issue in my app.
