### ISSUE TITLE
1.4.0 breaks for addons

### ISSUE THREAD

**Issue by dustinfarris** [ember-cli/ember-fetch#18]
Probably needs in included:

```js
    // see: https://github.com/ember-cli/ember-cli/issues/3718
    if (typeof(app.import) !== 'function' && app.app) {
      app = app.app;
    }
```

Also, even if I fix that part, it seems to conflict with ember-network/fetch somehow.  e.g. my addon uses ember-fetch.  my app uses the addon with ember-fetch and also ember-simple-auth which depends on ember-network.  If i add the above to ember-fetch for my addon , in my app ember-simple-auth starts throwing a fit about not being able to import fetch from ember-network.  Not sure how this is happening.

Downgrading ember-fetch to 1.3.0 makes it all go back to normal.

**Comment by nlfurniss** [comment]
`ember-network` has been deprecated, and ESA is using this project, so should no longer be an issue
