### ISSUE TITLE
Deprecate in favor of ember-network?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-fetch#21]
[ember-network](https://github.com/tomdale/ember-network) also provides `fetch` from `whatwg-fetch`, but it supports fastboot and browser environments.

Should we deprecate this addon in favor of that one?

**Comment by Turbo87** [comment]
it seems that `ember-fetch` is doing roughly the same: https://github.com/stefanpenner/ember-fetch/blob/f24cc4f28bb73542c11cb048fdb6ff31e1e06af5/index.js#L10-L13

**Comment by rwjblue** [comment]
Yep, which argues even more for deprecating one of them 😜

**Comment by tchak** [comment]
@rwjblue `ember-fetch` is much more uptodate then `ember-network`. I tried to make pull requests to `ember-network` but they were ignored. I am happy to help with whatever decision is made but I already ported once back and forth between both repositories. So if a clear decision is made on something, I will help. In the mean time I will continue to update `ember-fetch`.

**Comment by stefanpenner** [comment]
I believe ember-network was copied from here, with lofty goals of being more then just `fetch`. If it is just fetch, we should just use this one. If it is actually more we should use that one.

I would gladly maintain one, but not both...

**Comment by stefanpenner** [comment]
cc @tomdale whats your plan for ember-network

**Comment by stefanpenner** [comment]
My recommendation is to keep this one, as it is the original and continues to be maintained.

**Comment by stefanpenner** [comment]
flipped it around: https://github.com/tomdale/ember-network/issues/17

**Comment by rwjblue** [comment]
Agreed.

**Comment by tchak** [comment]
This is done on the `ember-network` side. Closing.
