### ISSUE TITLE
Force apps to declare whether they need the polyfill or not

### ISSUE THREAD

**Issue by nlfurniss** [ember-cli/ember-fetch#244]
Allowing apps to supply a list of supported browsers to this addon so that it can determine whether or not to include the polyfills is a small connivence, but isn't worth the performance penalty of including `caniuse`, which adds [46.9kb gzipped and minified](https://bundlephobia.com/result?p=caniuse-lite@1.0.30000939).

I propose we remove the feature and simply require consuming apps to [specify](https://github.com/ember-cli/ember-fetch/blob/master/README.md#allow-native-fetch) whether or not they need the polyfills to be included.

@xg-wang @stefanpenner

**Comment by xg-wang** [comment]
It's a build time dependency which should not be bundled to vendor file. And we do have an option for specifying whether or not they need the polyfills to be included: `alwaysIncludePolyfill` does that work for the need?

**Comment by nlfurniss** [comment]
Ah ok if it’s just build time then obv it’s fine
