### ISSUE TITLE
Deprecate + Remove Ember Data Functionality

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-fetch#289]
As of https://github.com/emberjs/data/pull/6077, ember-data will no longer depend on `ember-fetch` directly (but will continue to use it if it is present).

We should deprecate usage of all code in `addon/` except `addon/ajax.ts` (since it provides functionality for the ember-data adapter mixin, which will not be required as of ember-data@3.10+ and _possibly_ ember-data@3.9.2).

**Comment by xg-wang** [comment]
@rwjblue Does it makes sense to add deprecation when next ember-data LTS version (3.12) comes out then major bump to remove utils?

**Comment by rwjblue** [comment]
ember-data@3.9.2 was released dropping the dependency on `ember-fetch` (with some more tweaks coming in a 3.9.3).

**Comment by rwjblue** [comment]
> Does it makes sense to add deprecation when next ember-data LTS version (3.12) comes out then major bump to remove utils?

I don't think we have to be terribly concerned with the timing here; its probably fine to deprecate whenever we have the time...

**Comment by nlfurniss** [comment]
I should have chimed in earlier, sorry.

The utils are useful helpers in constructing one-off ajax requests using ember-fetch, so I'm concerned about deprecating them

**Comment by xg-wang** [comment]
@rwjblue @nlfurniss These utils are private in `ember-data`. How's your opinion on keeping them in `ember-fetch` and let `ember-data` depends/rollsup these?

**Comment by rwjblue** [comment]
`ember-data` should definitely not depend on this addon (that was the reason for my work in ember-data for 3.10.1).
