### ISSUE TITLE
A repo's description would be nice 😉

### ISSUE THREAD

**Issue by dcyriller** [ember-cli/ember-fetch#291]
![Capture d’écran 2019-05-02 à 20 19 56](https://user-images.githubusercontent.com/6677373/57097324-c2b79f80-6d17-11e9-950f-8f2e0f7512c5.png)

**Comment by stefanpenner** [comment]
Thanks, should be fixed:
![image](https://user-images.githubusercontent.com/1377/57098998-3b930900-6cd0-11e9-9ce2-7461e0c0a62d.png)


let me know if we can improve on it further
