### ISSUE TITLE
disabling fastboot asset generation

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-fetch#320]
After adding ember-fetch, I now see a `dist/ember-fetch/fetch-fastboot.js` generated after each build. I would like to disable this functionality as we do not use fastboot in our application.
Is this possible? 
If not, and we can agree it is worthwhile, I can help with a PR.

**Comment by xg-wang** [comment]
I think the [generation](https://github.com/ember-cli/ember-fetch/blob/v6.5.1/index.js#L132) can detect `ember-cli-fastboot` because the file is only [used](https://github.com/ember-cli/ember-fetch/blob/v6.5.1/index.js#L149) by fastboot.

**Comment by xg-wang** [comment]
https://github.com/ember-cli/ember-fetch/releases/tag/v7.1.0 won't generate fastboot asset if `ember-cli-fasboot` isn't installed or skipped by env flag
