### ISSUE TITLE
Using Request breaks in FastBoot

### ISSUE THREAD

**Issue by bobisjan** [ember-cli/ember-fetch#355]
`ember-fetch` supports FastBoot by patching URLs before it makes `fetch`.

https://github.com/ember-cli/ember-fetch/blob/408e6244dd30112edd96f130cdd350d490e97aed/public/fetch-fastboot.js#L49-L55

The problem is that `node-fetch` parses `input` argument in Request's [constructor](https://github.com/bitinn/node-fetch/blob/086be6fc74d8cc69faf76f65bf96d8f76b224dd1/src/request.js#L57-L70), so any changes made after that are not taken into account, and the request fails with `Only absolute URLs are supported` error.

Also, the `url` property is marked as read-only https://developer.mozilla.org/en-US/docs/Web/API/Request/url, so no changes should be made on that property.

**Comment by rwjblue** [comment]
Hmmm, yeah this seems somewhat fundamental :thinking:

@xg-wang - Any ideas / suggestions?

**Comment by xg-wang** [comment]
@rwjblue I have https://github.com/zonkyio/ember-fetch/pull/1 to the failing test PR @bobisjan posted, so it can be turned into a fix PR.

**Comment by bobisjan** [comment]
@xg-wang, @rwjblue thank you guys for fixing this 👏.
