### ISSUE TITLE
Thoughts on an ember-ajax compatible service?

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-fetch#398]
👋 

We are working on removing jQuery from our app, and thus moving from ember-ajax to ember-fetch, but we like a lot of the API of ember-ajax. Would you guys be interested in providing a compatible service that works with the ember-ajax API here or should that be a separate addon?

**Comment by burritoIand** [comment]
@rwwagner90 I created a barebones service that ~matches ember-ajax. It could be enhanced to add the other http aliases etc

**Comment by rwwagner90** [comment]
@burritoland we actually released an addon that is a full port of ember-Ajax to fetch. It’s https://github.com/expel-io/ember-ajax-fetch

**Comment by burritoIand** [comment]
very nice, should we close this?

**Comment by rwwagner90** [comment]
Yep, closing.
