### ISSUE TITLE
Where are all the response headers?

### ISSUE THREAD

**Issue by Redsandro** [ember-cli/ember-fetch#485]
I'm looking for certain (custom) headers in a server response.

```js
async probe(url) {
  const response = await fetch(url, {
    method: 'HEAD'
  })
  console.log('Res:', response)
},
```

The response object contains three headers: `["cache-control", "content-type", "expires"]`. 

There are however at least 10 headers in the actual response. You can see the request this function made in the Network tab of the Chrome or Firefox Developer Panel, and indeed it shows a dozen response headers.

How do I access these headers? Where did they go?

**Comment by xg-wang** [comment]
Some response headers are not exposed to JavaScript, can you give an example what headers you are trying to access?

**Comment by Redsandro** [comment]
Sorry, I forgot to update this issue. The problem is not with ember-fetch, it's a limitation of javascript/CORS. Like you say:

> Some response headers are not exposed to JavaScript

This is basically the answer. If I want to be able to see the other headers, the server needs to give permission with [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

This is one of those "feature, not bug" things.
