### ISSUE TITLE
Inconsistent Headers objects with preferNative

### ISSUE THREAD

**Issue by hoIIer** [ember-cli/ember-fetch#486]
The readme has one line that mentions headers and how to import the Headers object:

`import fetch, { Headers, Request, Response, AbortController } from 'fetch';`

When using `preferNative: false` (default), the Headers object comes from the underlying polyfill lib and contains a key `.map` that stores the raw headers object.
https://github.com/github/fetch/blob/master/fetch.js#L79

When using `preferNative: true`, the imported `Headers` is a raw javascript object and thus doesn't have a .map to match the polyfill version.

This seems inconsistent and is undocumented in the readme.

Ideally the imported `Headers` would always be a [native headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers) or matching polyfill.

**Comment by xg-wang** [comment]
`Headers.map` is not documented https://github.github.io/fetch/#Headers. But it probably means a private field not intended being used. `ember-fetch` mentioned itself is a wrapper for fetch polyfill.
The `preferNative` option will let the imported APIs be native ones if exist.
When setting `preferNative=true`, is the expectation to return `undefined` when browser does not suppport `fetch` and `Headers`?
