### ISSUE TITLE
`Import fetch from 'fetch'` not working w/ 3.2.8

### ISSUE THREAD

**Issue by BlueRaja** [ember-cli/ember-fetch#55]
Running `ember-fetch` in a Fastboot enabled app, we see the same issue mentioned in https://github.com/ember-cli/ember-fetch/issues/26

Running without Fastboot works fine.

The project is huge so I'm not sure if this is a straight-up an `ember-fetch` issue, or a complex mix of other factors.  We don't have any dependencies relying on `ember-network`.

**Comment by kratiahuja** [comment]
@BlueRaja it would be great if you could provide a minimal reproduction of this issue.

**Comment by knownasilya** [comment]
I see something else, also with 3.2.8

```
ember.debug.js:30911 Error while processing route: dashboard.index FastBoot is not defined ReferenceError: FastBoot is not defined
    at Module.callback (http://stocktonca.mg.dev/engines-dist/dashboard/ember-fetch/fastboot-fetch.js:3:17)
    at Module.exports (http://stocktonca.mg.dev/assets/vendor.js:4574:32)
    at Module._reify (http://stocktonca.mg.dev/assets/vendor.js:4609:59)
    at Module.reify (http://stocktonca.mg.dev/assets/vendor.js:4596:27)
    at Module.exports (http://stocktonca.mg.dev/assets/vendor.js:4572:10)
    at requireModule (http://stocktonca.mg.dev/assets/vendor.js:4498:18)
    at Class._extractDefaultExport (http://stocktonca.mg.dev/assets/vendor.js:214159:20)
    at Class.resolveOther (http://stocktonca.mg.dev/assets/vendor.js:213880:32)
    at Class.superWrapper [as resolveOther] (http://stocktonca.mg.dev/assets/vendor.js:64685:22)
    at Class.resolve (http://stocktonca.mg.dev/assets/vendor.js:29029:35)
```

**Comment by knownasilya** [comment]
Looks like https://github.com/ember-cli/ember-fetch/blob/master/index.js#L84 targets `vendor/*` but the fastboot fetch was moved to `public/`

**Comment by kratiahuja** [comment]
@knownasilya That's the browser version which is wrapped with `if (typeof FastBoot === 'undefined') {..}` check. The Node version of fetch is present in the manifest here: https://github.com/ember-cli/ember-fetch/blob/master/index.js#L91. What's ESA?

From your stack trace it seems sandbox globals in FastBoot aren't being set. Can you put in a minimal reproduction? I would be happy to look into it.

**Comment by knownasilya** [comment]
I'm not running Fastboot, that's the problem 😄 ESA is Ember Simple Auth, like #26 mentions might be related. But I think this is a different issue.

**Comment by sandydoo** [comment]
Ran into this issue trying to move from `ember-network` on a pre-1.0 version of FastBoot. Quick review of what I found + solution:

b9be38f2da9fd6d48e7b285ed0b7a565d6c44d17 added support for the new v1.0 FastBoot (with the new manifest hook), but also completely removed support for legacy FastBoot by removing the conditional logic that injects the FastBoot shim into the FastBoot vendor tree. 😢 

This means that if you're running an older version of `ember-cli-fastboot`, happily avoiding the breaking changes in some or all of your favourite addons, `fetch` won't be inserted into your FastBoot build. Should you need to stick to pre-1.0 for a while longer, one solution is to undo the deleted parts of that commit (verified it works) or just update `ember-cli-fastboot` to at least`v1.0.0-beta.18` (personally went with `beta.19`), which [exposes](https://github.com/ember-fastboot/ember-cli-fastboot/commit/0b992fcabf9950579f6ae9f61be46aef4d81d0df) the `updateFastBootManifest` hook to addons without breaking anything (in theory).

**Comment by samselikoff** [comment]
I ran into the same issue, the only way I could solve it was by having the host app install `ember-fetch` themselves (even though it's listed as a `dependency` in my addon).

Would a repro still help here?

**Comment by jkeen** [comment]
Also ran into this issue and got around it the same way Sam did above ^

**Comment by xg-wang** [comment]
@samselikoff @jkeen Can you verify the issue you have are duplicates of #98 or the pre-1.0 Fastboot one?

**Comment by samselikoff** [comment]
Seems like if the rule is for top-level app to have this installed, then this can be closed 👍

**Comment by xg-wang** [comment]
If someone still sees this issue feel free to open another issue or comment to re-open.
