### ISSUE TITLE
Fastboot dependency whitelisting

### ISSUE THREAD

**Issue by willviles** [ember-cli/ember-fetch#62]
Since Ember Fetch `1.4.2`, there appears to be an issue with using the `import fetch from 'fetch'` syntax in Fastboot apps, requiring a change to the fastboot dependency whitelist in package.json. 

This issue relates to Ember Simple Auth, which has broken session restoration for Fastboot apps ever since upgrading to a later version of Ember Fetch. More details: https://github.com/simplabs/ember-simple-auth/issues/1138#issuecomment-319684132.

The fix appears to be to change `"node-fetch"` to just `"fetch"` in the app's `fastbootDependencies`. I'm just wondering whether that's an anticipated requirement for using Ember Fetch since defining `fetch` as a module import ([see here](https://github.com/ember-cli/ember-fetch/blob/994c0df4183185a812e0b096f79af3f26ed71937/public/fastboot-fetch.js#L2)) and whether it should be mentioned in the docs?

**Comment by nlfurniss** [comment]
@kratiahuja @stefanpenner any thoughts on this?

**Comment by jobackman** [comment]
Any more thoughts on whether requiring fetch is an anticipated requirement? 

I ran into this issue recently and found my way here by https://github.com/simplabs/ember-simple-auth/issues/1138 and can also confirm that adding `"fetch"` as a fastboot dependency solved it for me as well.

**Comment by lougreenwood** [comment]
Any movement on this issue?

**Comment by xg-wang** [comment]
This should be fixed by doing `ember install ember-fetch` at app.
