### ISSUE TITLE
appveyor failing due to Firefox

### ISSUE THREAD

**Issue by nlfurniss** [ember-cli/ember-fetch#81]
Looks like this started failing after bf7575014f045ad6a39de0c035d0366e03df4abe. @tchak can you investigate.

Sample Appveyor test output
```
ok 44 PhantomJS 2.1 - Unit | Mixin | adapter-fetch: ajaxOptions returns the correct data
not ok 45 Firefox - error
    ---
        message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            
        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 30s. testem.js not loaded?' }
    ...
ok 46 Chrome 60.0 - ESLint | addon: ember-fetch/ajax.js
ok 47 Chrome 60.0 - ESLint | addon: ember-fetch/mixins/adapter-fetch.js
ok 48 Chrome 60.0 - Acceptance: Root: visiting /
```
[Link to test output](https://ci.appveyor.com/project/embercli/ember-fetch/build/194/job/0cyptlpij9hpaxny)

**Comment by tchak** [comment]
Yep, sorry about that. I will fix this.

**Comment by nlfurniss** [comment]
Another thing I've found is that the `browser_args` that were added now don't allow test debugging via chrome.

when you now run `ember test -server`, these args open chrome in a headless state and you can't use its dev tools to debug

```
  browser_args: {
     Firefox: ['-headless'],
     Chrome: [
       '--disable-gpu',
       '--headless',
       '--remote-debugging-port=9222',
       '--window-size=1440,900'
     ]
   }
```

**Comment by rwjblue** [comment]
See current ember-cli blueprint, we have tweaked the settings slightly so that headless chrome is only used in CI.

**Comment by nlfurniss** [comment]
Thanks for fixing @tchak!
