### ISSUE TITLE
adapter mixin clobbers contentType in JSONAPIAdapter

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-fetch#87]
It clobbers this https://github.com/emberjs/data/blob/v2.14.10/addon/adapters/json-api.js#L162.

**Comment by nlfurniss** [comment]
I'm a little confused by that bit. If `contentType` is set to anything, overwrite it and set it to `application/vnd.api+json`?

```js
if (hash.contentType) {
  hash.contentType = 'application/vnd.api+json';
}
```

**Comment by kellyselden** [comment]
That shouldn't be required though. The mixin should just inherit the contentType from the adapter it's on (via a _super call).

**Comment by rwwagner90** [comment]
Just hit this issue as well. Anyone have a fix?

**Comment by webark** [comment]
https://github.com/ember-cli/ember-fetch/blob/master/addon/mixins/adapter-fetch.js#L127-L130

looks like this needs to get cleaned up. You could write your own mixin that extends this one, and overwrite the ajax options method.

**Comment by youroff** [comment]
Not sure if this is this exact issue, but we can't make ember-fetch working with ember-simple-auth and jsonapi adapter. Seems like AdapterFetch mixin doesn't call `this._super` anywhere in ajaxOptions which doesn't let simple auth do its job. Proper content type is getting cleared out in our case too. Any ideas on workaround?

**Comment by webark** [comment]
@youroff might not be a bad idea to include. However, i think if you include ember-fetch mixin first in your application adapter, it shouldn’t overwrite. Id imagine that the mixins get called in the order you list them.

**Comment by youroff** [comment]
Yeah, I tried to change the order, but it didn't help. Might be something else. I'll post here if I find anything.

**Comment by ChristopherConnock** [comment]
@youroff running into a similar error switching to ember-fetch (with a fully operational ember-auth app).

ember-auth's authorize is not called (order of mixins did not change anything)
`export default DS.RESTAdapter.extend(AdapterFetch, DataAdapterMixin, {`

ember-auth's authorize is called, but fetch is not leveraged
`export default DS.RESTAdapter.extend(DataAdapterMixin, {`

**Comment by youroff** [comment]
@ChristopherConnock interesting, I thought it only affected JSONAPIAdapter. Anyways, we decided to put it on hold until fetch gets better support. So far even ember-data won't allow to ditch $.ajax completely if I get it right.

**Comment by tchak** [comment]
I just want to mention that we are moving fetch support to Ember Data itself : https://github.com/emberjs/data/pull/5386
