### ISSUE TITLE
problem with AdapterFetch when fast boot is enabled

### ISSUE THREAD

**Issue by javierarpa** [ember-cli/ember-fetch#97]
App is being served by FastBoot
DEBUG: -------------------------------
DEBUG: Ember           : 2.17.0
DEBUG: Ember Data      : 2.17.0
DEBUG: Ember Bootstrap : 1.0.0
DEBUG: -------------------------------
TypeError: Cannot read property 'catch' of undefined
    at Class.ajax (/Users/javierarpa/desa/tourme/tourme/tmp/broccoli_merge_trees-output_path-JCZ0mPSY.tmp/assets/addon-tree-output/ember-fetch/mixins/adapter-fetch.js:211:1)
    at Class.findAll (/Users/javierarpa/desa/tourme/tourme/tmp/broccoli_merge_trees-output_path-JCZ0mPSY.tmp/assets/addon-tree-output/modules/ember-data/adapters/rest.js:364:1)

if fast boot is disabled, all work fine. it seems a problem with the import of the fetch on ember-fetch/mixins/adapter-fetch.js

Adapter:
--------
export default RESTAdapter.extend(AdapterFetch, {
	namespace: 'api/v1/col',
	host: 'https://zzzz.zzzzz.net:4285'
});

Route:
--------
  model() {
    return this.get('store').findAll('city');
  },

**Comment by nlfurniss** [comment]
Hey @javierarpa, the issue is with an initializer that Fastboot uses to swap in node ajax functionality (specifically [this line](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js#L33)).

You can fix this by defining your own initializer like so:

```
app/
├── initializers/
    └── ajax.js

// ajax.js
export default {
  name: 'ajax-service',
  initialize() {
    // noop to override fastboot's initializer
  }
}
```

**Comment by javierarpa** [comment]
Thank you very much! It did work as expected, great.

**Comment by nlfurniss** [comment]
@javierarpa did you put the initializer in `app/initializers` or `fastboot/initializers`?

**Comment by javierarpa** [comment]
@nlfurniss  Where you suggested, in `app/initializers`.

**Comment by nlfurniss** [comment]
what version of fastboot are you running?

**Comment by javierarpa** [comment]
ember-cli-fastboot@1.1.2

DEBUG: Ember           : 2.18.0
DEBUG: Ember Data      : 2.18.0
DEBUG: jQuery          : 3.3.1
DEBUG: Ember Bootstrap : 1.2.0

app/initializers
```
//ajax.js
export function initialize(/* application */) {
  // application.inject('route', 'foo', 'service:foo');
}

export default {
  initialize
};
```

**Comment by javierarpa** [comment]
@nlfurniss  You're right, I finally had to comment the line in fastboot directory. Sorry I was trying on another project and I got confused.
