### ISSUE TITLE
Don't work as dependencies

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-fetch#98]
`ember-fecth` does not work in my consumer app with Fastboot enabled, when I put ember-fetch as `dependencies` in my addon

cosumer app - https://github.com/villander/ember-mvp
addon - https://github.com/villander/ember-apollo-client/blob/apollo-client-2.0/package.json#L34

looks like ember-fetch specifically doesn’t work with fastboot when it’s a nested dependency
because its `updateFastBootManifest()` method is never called

the question is what happens when you wind up calling that hook multiple times?
like if `ember-mvp` and `ember-apollo-client` both have `ember-fetch` installed, does it get called twice?

is it `ember-fetch`’s responsibility to guard against that?

**Comment by stefanpenner** [comment]
@kratiahuja got any cycles?

**Comment by villander** [comment]
@kratiahuja can you help us with that? or some hint of how to solve it, I can work on it if I know the cause

**Comment by dfreeman** [comment]
I opened up https://github.com/ember-fastboot/ember-cli-fastboot/issues/597 to try and start driving toward a solution here. @stefanpenner @kratiahuja would love to get your thoughts

**Comment by xg-wang** [comment]
Close as mentioned in #126 
We can re-open if we can leverage new API for a better solution.
