### ISSUE TITLE
indicating progress

### ISSUE THREAD

**Issue by st-h** [ember-cli/ember-fetch#99]
This ticket is similar to the already closed https://github.com/ember-cli/ember-fetch/issues/53, however as ember is moving towards making jQuery optional, we are going to need a feature complete replacement for making XmlHttpRequests. Currently the lack of displaying progress is blocking  some people from using ember-fetch as such a replacement. Even though it seems that progress will not be supported when the polyfill is used, I think it is important to add this feature in order to allow projects that target up to date browser to make usage of this addon.

I can put some time into putting together a PR, but as there are other aspects involved like #63 or #45, I think it is best to agree on an approach and details first.

**Comment by nlfurniss** [comment]
Unfortunately, unless the `fetch` spec allows for indicating progress, this is something you will have to continue to use XmlHttpRequest for.

**Comment by xg-wang** [comment]
For more info on spec: 
- https://github.com/whatwg/fetch/issues/21
- https://github.com/whatwg/fetch/issues/607
